version: 2.1

orbs:
  python: circleci/python@2.1.1
  aws-sam-serverless: circleci/aws-sam-serverless@6.1.0
  aws-cli: circleci/aws-cli@5.2.0


jobs:
  build-deploy:
    docker:
      - image: cimg/python:3.11
    steps:
      - checkout  # Checkout the code from the repository

      - run:
          name: Install uv
          command: pip install uv  # Install uv package

      - run:
          name: Install the project
          command: uv sync --all-extras  # Sync the project using uv

      - run:
          name: Run tests
          command: uv run pytest  # Run pytest tests

      - run:
          name: Set up AWS CLI
          command: |
            pip install awscli  # Install AWS CLI
      

      - run:
          name: Build Lambda Deployment Package
          command: |
            chmod +x build-sam.sh
            ./build-sam.sh  # Execute the build script

      - aws-sam-serverless/sam-build:  # Use the aws-sam-serverless orb to build the SAM package
          build-dir: ./build  # Customize the build directory if needed

      - aws-sam-serverless/sam-deploy:  # Use the aws-sam-serverless orb to deploy with SAM
          stack-name: sam-app
          capabilities: CAPABILITY_IAM
          region: eu-central-1
          resolve-s3: true

      - run:
          name: Output API Gateway URL
          command: |
            API_URL=$(aws cloudformation describe-stacks --stack-name sam-app)
            echo "GenAI API URL: $API_URL"  # Output the API Gateway URL

workflows:
  version: 2
  deploy:
    jobs:
      - build-deploy  # Trigger the build-deploy job in the workflow
