version: 2.1

orbs:
  python: circleci/python@2.1.1

jobs:
  build-deploy:
    docker:
      - image: cimg/python:3.11
    steps:
      - checkout  # Checkout the code from the repository

      - run:
          name: Install uv
          command: pip install uv  # Install uv package

      - run:
          name: Install the project
          command: uv sync --all-extras  # Sync the project using uv

      - run:
          name: Run tests
          command: uv run pytest  # Run pytest tests

      - run:
          name: Set up AWS CLI
          command: |
            pip install awscli  # Install AWS CLI
      
      - run:
          name: Install AWS SAM CLI
          command: |
            curl -sSL https://github.com/aws/aws-sam-cli/releases/latest/download/aws-sam-cli-linux-x86_64.zip -o sam-installation.sh
            chmod +x sam-installation.sh
            sudo ./sam-installation.sh/install  # Install AWS SAM CLI


      - run:
          name: Build Lambda Deployment Package
          command: |
            chmod +x build-sam.sh
            ./build-sam.sh  # Execute the build script

      - run:
          name: Build with SAM
          command: sam build  # Build with SAM

      - run:
          name: Deploy with SAM
          command: |
            sam deploy --stack-name sam-app --resolve-s3 --capabilities CAPABILITY_IAM --region eu-central-1  # Deploy with SAM

      - run:
          name: Output API Gateway URL
          command: |
            API_URL=$(aws cloudformation describe-stacks --stack-name sam-app)
            echo "GenAI API URL: $API_URL"  # Output the API Gateway URL

workflows:
  version: 2
  deploy:
    jobs:
      - build-deploy  # Trigger the build-deploy job in the workflow
