version: 2.1

executors:
  python-executor:
    docker:
      - image: circleci/python:3.11  # Use a Docker image with Python 3.11
    working_directory: ~/repo  # Set the working directory to the repository

jobs:
  build-deploy:
    executor: python-executor
    steps:
      - checkout  # Checkout the code from the repository

      - run:
          name: Install uv
          command: pip install uv  # Install uv package

      - run:
          name: Install the project
          command: uv sync --all-extras  # Sync the project using uv

      - run:
          name: Run tests
          command: uv run pytest  # Run pytest tests

      - run:
          name: Set up AWS CLI
          command: |
            pip install awscli  # Install AWS CLI

      - run:
          name: Build Lambda Deployment Package
          command: |
            chmod +x build-sam.sh
            ./build-sam.sh  # Execute the build script

      - run:
          name: Build with SAM
          command: sam build  # Build with SAM

      - run:
          name: Deploy with SAM
          command: |
            sam deploy --stack-name sam-app --resolve-s3 --capabilities CAPABILITY_IAM --region eu-central-1  # Deploy with SAM

      - run:
          name: Output API Gateway URL
          command: |
            API_URL=$(aws cloudformation describe-stacks --stack-name sam-app --query "Stacks[0].Outputs[?OutputKey=='ApiUrl'].OutputValue" --output text)
            echo "GenAI API URL: $API_URL"  # Output the API Gateway URL

workflows:
  version: 2
  deploy:
    jobs:
      - build-deploy  # Trigger the build-deploy job in the workflow
